[DEFAULT]
LogLevel = DbConfig

[Database]
Host = 10.110.149.140
Port = 30014
User = sysdba
Password =Dev@20230725
DatabaseName= igdp_v3_dev

[table]
tableName_tested=web_auto_test_input
test_result_table=web_auto_test
web_inspection_info=web_inspection_info
web_inspection_submenu=web_inspection_submenu
web_auto_task_summary=web_auto_task_summary
[test_website]
website_url=http://10.110.117.59:30018/portal/workbench
; website_username=superAdmin
; website_password=igdp.0430.IXV.!#

website_username=u202407100000004903
website_password=Lyl@15589913339


[time_script]
timed=15:22
scriptAddress=./test.py