-- 农田管理系统数据库表结构

-- 用户表
CREATE TABLE `user` (
  `USER_ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '用户ID',
  `ACCOUNT` varchar(50) NOT NULL COMMENT '账号（登录名）',
  `PASSWORD` varchar(100) NOT NULL COMMENT '密码',
  `USER_NAME` varchar(50) NOT NULL COMMENT '姓名',
  `ID_CARD` varchar(18) DEFAULT NULL COMMENT '身份证号',
  `GENDER` varchar(10) DEFAULT NULL COMMENT '性别',
  `PHONE` varchar(20) DEFAULT NULL COMMENT '手机号',
  `EMAIL` varchar(100) DEFAULT NULL COMMENT '邮箱',
  `AD_CODE` varchar(20) DEFAULT NULL COMMENT '行政区划代码',
  `REG_DATE` datetime DEFAULT NULL COMMENT '注册时间',
  `STATUS` int(1) DEFAULT '1' COMMENT '账号状态 (1:正常, 0:禁用)',
  PRIMARY KEY (`USER_ID`),
  UNIQUE KEY `UK_ACCOUNT` (`ACCOUNT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';

-- 农民认证表
CREATE TABLE `farmer_certification` (
  `CERT_ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '认证ID',
  `USER_ID` bigint(20) NOT NULL COMMENT '用户ID',
  `REAL_NAME` varchar(50) NOT NULL COMMENT '真实姓名',
  `ID_CARD` varchar(18) NOT NULL COMMENT '身份证号',
  `AD_CODE` varchar(20) DEFAULT NULL COMMENT '行政区划代码',
  `FARM_TYPE` varchar(50) DEFAULT NULL COMMENT '种植类型',
  `CERT_DOC_PATH` varchar(200) DEFAULT NULL COMMENT '证明文件存储路径',
  `DETAIL_ADDRESS` varchar(200) DEFAULT NULL COMMENT '详细住址',
  `APPLY_TIME` datetime NOT NULL COMMENT '申请时间',
  `STATUS` int(1) DEFAULT '1' COMMENT '认证状态 (1:审核中, 2:已通过, 0:未通过)',
  `APPROVER_ID` bigint(20) DEFAULT NULL COMMENT '审批人ID',
  `APPROVE_TIME` datetime DEFAULT NULL COMMENT '审批时间',
  `REJECT_REASON` varchar(200) DEFAULT NULL COMMENT '驳回原因',
  PRIMARY KEY (`CERT_ID`),
  KEY `IDX_USER_ID` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='农民认证表';

-- 土地信息表
CREATE TABLE `land_info` (
  `LAND_ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '土地ID',
  `LAND_NAME` varchar(100) NOT NULL COMMENT '地块名称',
  `OWNER_TYPE` varchar(20) NOT NULL COMMENT '土地权属',
  `AD_CODE` varchar(20) DEFAULT NULL COMMENT '行政区划代码',
  `DETAIL_ADDRESS` varchar(200) DEFAULT NULL COMMENT '详细地址',
  `AREA_SIZE` decimal(10,2) DEFAULT NULL COMMENT '地块面积',
  `LAND_TYPE` varchar(20) DEFAULT NULL COMMENT '地块类型',
  `CURRENT_STATUS` varchar(20) DEFAULT NULL COMMENT '当前状态',
  `LATITUDE` decimal(10,6) DEFAULT NULL COMMENT '纬度',
  `LONGITUDE` decimal(10,6) DEFAULT NULL COMMENT '经度',
  `FARMER_USER_ID` bigint(20) NOT NULL COMMENT '关联农民用户ID',
  `CREATE_BY` bigint(20) DEFAULT NULL COMMENT '创建人ID',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `UPDATE_TIME` datetime DEFAULT NULL COMMENT '最后更新时间',
  `REMARK` varchar(200) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`LAND_ID`),
  KEY `IDX_FARMER_USER_ID` (`FARMER_USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='土地信息表';